# Generated by Django 4.0 on 2022-01-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('images', models.ImageField(default='avatar.jpg', upload_to='profile_Images')),
                ('student', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('department', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
