# Generated by Django 4.0 on 2022-01-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='roll_no',
        ),
    ]
