# Generated by Django 4.0 on 2022-02-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
