# Generated by Django 3.2.5 on 2022-02-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_student_info_rollno'),
        ('classes', '0004_auto_20220214_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_info')),
            ],
            options={
                'verbose_name_plural': 'Assessments',
            },
        ),
    ]
