# Generated by Django 3.2.5 on 2022-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_student_alter_classes_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='alias',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
