# Generated by Django 3.2.5 on 2022-02-14 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_alias'),
        ('classes', '0003_classes_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_name',
        ),
        migrations.AddField(
            model_name='classes',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
