# Generated by Django 3.2.5 on 2022-03-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_rename_batch_batch_name'),
        ('section', '0004_rename_section_section_name'),
        ('classes', '0004_auto_20220214_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batch'),
        ),
        migrations.AddField(
            model_name='classes',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='section.section'),
        ),
    ]
