# Generated by Django 4.0 on 2022-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(max_length=15)),
                ('year', models.PositiveSmallIntegerField()),
                ('part', models.CharField(max_length=10)),
                ('sem_start_date', models.DateField()),
                ('sem_end_date', models.DateField()),
            ],
        ),
    ]
