# Generated by Django 3.2.5 on 2022-02-15 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='publish_to',
        ),
        migrations.AddField(
            model_name='notification',
            name='publish_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
