# Generated by Django 3.2.5 on 2022-02-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_auto_20220215_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='publish_to',
        ),
        migrations.AddField(
            model_name='notification',
            name='publish_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customuser.user'),
            preserve_default=False,
        ),
    ]
