# Generated by Django 4.0 on 2022-02-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_section_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='section',
            name='department',
        ),
    ]
