# Generated by Django 4.0 on 2022-02-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_remove_section_batch_remove_section_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section',
            new_name='name',
        ),
    ]
