# Generated by Django 4.0 on 2022-02-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_remove_batch_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch',
            new_name='name',
        ),
    ]
