# Generated by Django 4.0 on 2022-01-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_classes_student_alter_classes_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, null=True)),
                ('upload', models.FileField(default='avatar.jpg', upload_to='materials')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
            options={
                'verbose_name_plural': 'material_name',
            },
        ),
    ]
