# Generated by Django 3.2.5 on 2022-02-12 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_classes_student_alter_classes_teacher'),
        ('class_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name_plural': 'materials'},
        ),
        migrations.RemoveField(
            model_name='materials',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='upload',
        ),
        migrations.AddField(
            model_name='materials',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='file',
            field=models.FileField(default='avatar.jpg', upload_to='materials/'),
        ),
        migrations.AddField(
            model_name='materials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('materials', models.ManyToManyField(to='class_materials.materials')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'folder',
            },
        ),
    ]
