# Generated by Django 3.2.5 on 2022-02-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_student_alter_classes_teacher'),
        ('class_materials', '0002_auto_20220212_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='materials',
            field=models.ManyToManyField(related_name='materials', to='class_materials.materials'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
