# Generated by Django 4.0 on 2022-02-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0009_user_password_changed'),
        ('classes', '0002_classes_student_alter_classes_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Give_Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_files', models.FileField(upload_to='assignments_given')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.user')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='Submit_Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_files', models.FileField(upload_to='assignments_submitted')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.give_assignments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.user')),
            ],
            options={
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
