# Generated by Django 4.0 on 2022-02-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='give_assignments',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Assignments'},
        ),
    ]
