# Generated by Django 4.0 on 2022-02-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_give_assignments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give_assignments',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
