# Generated by Django 3.2.5 on 2022-02-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_give_assignments_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give_assignments',
            name='completed',
        ),
    ]
