# Generated by Django 3.2.5 on 2022-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_auto_20220217_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='give_assignments',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterField(
            model_name='give_assignments',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
