# Generated by Django 3.2.5 on 2022-02-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20220217_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_assignments',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
