# Generated by Django 4.0 on 2022-02-08 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0008_excelfileupload'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='publish_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customuser.user'),
            preserve_default=False,
        ),
    ]
