# Generated by Django 3.2.5 on 2022-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_notice',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
