# Generated by Django 3.2.5 on 2022-03-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_global_notice_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='global_notice',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Global Notices'},
        ),
    ]
