# Generated by Django 3.2.5 on 2022-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_publish_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish_by',
            field=models.CharField(max_length=100),
        ),
    ]
