# Generated by Django 3.2.5 on 2022-03-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_global_notice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department_notice',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Department Notices'},
        ),
    ]
