# Generated by Django 3.2.5 on 2022-02-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_global_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
