# Generated by Django 3.2.5 on 2022-02-17 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20220214_0918'),
        ('assignments', '0004_remove_give_assignments_completed'),
        ('notice', '0005_alter_notice_publish_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignmentnotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.FileField(blank=True, upload_to='notice/files/')),
                ('publish_by', models.CharField(blank=True, max_length=100, null=True)),
                ('assignmment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.give_assignments')),
                ('publish_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
            options={
                'verbose_name_plural': 'Notices',
            },
        ),
    ]
