# Generated by Django 3.2.5 on 2022-02-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_assignmentnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentnotice',
            name='files',
        ),
    ]
