# Generated by Django 3.2.5 on 2022-02-17 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0007_remove_assignmentnotice_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentnotice',
            old_name='assignmment',
            new_name='assignment',
        ),
        migrations.AlterField(
            model_name='assignmentnotice',
            name='publish_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customuser.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='global_notice',
            name='publish_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customuser.user'),
            preserve_default=False,
        ),
    ]
