# Generated by Django 4.0 on 2022-01-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_user_dob'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_info',
            options={'verbose_name_plural': 'student_info'},
        ),
        migrations.AddField(
            model_name='student_info',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customuser.user'),
            preserve_default=False,
        ),
    ]
