# Generated by Django 4.0 on 2022-02-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_info_options_student_info_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='batch',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='department',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='section',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
