# Generated by Django 4.0 on 2022-02-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_remove_batch_department'),
        ('department', '0001_initial'),
        ('section', '0003_remove_section_batch_remove_section_department'),
        ('student', '0003_alter_student_info_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='batch.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_info',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_info',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='section.section'),
            preserve_default=False,
        ),
    ]
