# Generated by Django 4.0 on 2022-02-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_info_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='rollno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
