# Generated by Django 3.2.5 on 2022-03-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0005_auto_20220311_0959'),
        ('student', '0006_student_info_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_info')),
            ],
            options={
                'verbose_name_plural': 'attendance',
            },
        ),
    ]
