# Generated by Django 3.2.5 on 2022-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_rename_department_name_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='alias',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
